#theme: jekyll-skeleton
title: "altctrls.info"
author: "This is a community effort, please check the list of [contributors](#contributors)."
description: "A list of resources for creating alternative controllers, playful installations and physical-digital hybrids"
email: "enricllagostera@gmail.com"
