#theme: jekyll-skeleton
title: "awesome-altctrls!"
author: "This is a community effort, please check the list of [contributors]()."
description: "A list of resources for making alternative controllers, playful installations and physical-digital hybrids"
email: "enricllagostera@gmail.com"